
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbjvkqjfsbbtwhluxaqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ianZrcWpmc2JidHdobHV4YXFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMDE2NTYsImV4cCI6MjA1NzY3NzY1Nn0.b1b39GiR-w-jml95SfYHVZfxaHVXAScUGcGEiQmkrJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Initialize the Supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// NOTE: Bucket creation is now handled through SQL migrations
// We don't need to try to create the bucket here - it will be created by SQL
const checkPdfBucket = async () => {
  try {
    const { data: buckets, error } = await supabase.storage.listBuckets();
    
    if (error) {
      console.error('Error checking storage buckets:', error);
      return;
    }
    
    const pdfBucketExists = buckets.some(bucket => bucket.name === 'pdfs');
    
    if (pdfBucketExists) {
      console.log('PDF bucket exists and is ready to use.');
    } else {
      console.log('PDF bucket does not exist yet. It needs to be created via SQL migrations.');
    }
  } catch (e) {
    console.error('Error checking PDF bucket:', e);
  }
};

// Call the function to check bucket existence
checkPdfBucket();

export { SUPABASE_URL };
